language: node_js
node_js: 
- "stable"
script: npm test

after_success:
- npm run coverage
services:
  - postgresql
  
addons:
  postgresql: "9.6"

  before_script:
  - DROP DATABASE IF EXISTS banka
  - psql -c 'create database banka;' -U postgres
